/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/check-health`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-3`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-4`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-5`; params?: Router.UnknownInputParams; } | { pathname: `/register-with-code`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/check-health`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding-1`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding-2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding-3`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding-4`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding-5`; params?: Router.UnknownOutputParams; } | { pathname: `/register-with-code`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/check-health${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding-1${`?${string}` | `#${string}` | ''}` | `/onboarding-2${`?${string}` | `#${string}` | ''}` | `/onboarding-3${`?${string}` | `#${string}` | ''}` | `/onboarding-4${`?${string}` | `#${string}` | ''}` | `/onboarding-5${`?${string}` | `#${string}` | ''}` | `/register-with-code${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/check-health`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-3`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-4`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding-5`; params?: Router.UnknownInputParams; } | { pathname: `/register-with-code`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
